### ISSUE TITLE
publish on PyPI

### ISSUE THREAD

**Issue by ausgerechnet** [fau-klue/pandas-association-measures#14]
it would make my life easier if you'd publish the package to PyPI …

**Comment by ausgerechnet** [comment]
- v0.1.5 fixes the performance issues

**Comment by ausgerechnet** [comment]
I don't know how to improve performance of the hypergeometric likelihood though. May be you can have a look at it @martialblog?

Anyway, it would be *amazing* if you could publish the current version (v0.1.5) to PyPI …

**Comment by martialblog** [comment]
Done. If you give me your PyPi handle I can make you collaborator there

**Comment by ausgerechnet** [comment]
amazing – thank you!

https://pypi.org/user/ausgerechnet/
