### ISSUE TITLE
Feature request: Specify input frequencies from a keyword analysis perspective

### ISSUE THREAD

**Issue by tsproisl** [fau-klue/pandas-association-measures#23]
Currently, input frequencies need to be specified in one of two formats:
- Fields of the contingency table (O_11, O12, O21, O22)
- Frequency signature (f, f1, f2, N)

For keyword analyses, it would be more natural to specify the frequencies of the keyword in both texts (f1, f2) and the lengths of the two texts (N1, N2), i.e.:
- f1 = O11
- f2 = O21
- N1 = R1
- N2 = R2

In the literature, the frequencies are usually referred to as f1, f2, N1, N2 – but I do not know if that wouldn’t cause too much confusion with frequency signatures (f, f1, f2, N). In any case, it would be very convenient to have an input option suitable to the needs of keyword analyses.

**Comment by ausgerechnet** [comment]
closed in PR #24
